image: node:12

cache:
  paths:
    - node_modules/

stages:
  - build
  - test

webpack:
  stage: build
  script:
    - npm install
    - npm run build
  tags:
    - docker

jest:
  stage: test
  script:
   - npm run test
  tags:
    - docker
