image: node:12

# https://docs.gitlab.com/ee/ci/caching/#caching-nodejs-dependencies
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

stages:
  - build
  - test

webpack:
  stage: build
  script:
    - npm install
    - npm run build

jest:
  stage: test
  script:
   - npm run test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/

eslint:
  stage: test
  script:
    - npm run lint
